### ISSUE TITLE
How to use this library in multiple threads?

### ISSUE THREAD

**Issue by zaafar** [zaafar/ClickableTransparentOverlay#14]
The current demo shows single threaded application with Coroutine. Would be nice to see if this library can be used by multi-threaded application and how.

**Comment by Amiron49** [comment]
Currently I'm prototyping an application and pretty much copy pasted your overlay implementation so I could do quick adjustments to it without the need of long winded merge requests. Now I'm at a point where I'm happy with my alterations to your overlay code and would like to contribute things back and hopefully delete my copy pasted version from my code and use your nuget instead.

If you haven't started working on this issue yet I could implement what I did for threading

**Comment by zaafar** [comment]
Sure! Go for it.
