### ISSUE TITLE
Different console window supression

### ISSUE THREAD

**Issue by Amiron49** [zaafar/ClickableTransparentOverlay#16]
right now the `static bool TerminalWindow` in Overlay.cs is responsible for toggling the console window away. But the ClickableTransparentOverlay assembly is not the one responsible for spawning it.

Changing the OutputType of DriverProgram.csproj to `WinExe` would be cleaner

```xml
<PropertyGroup>
   <OutputType>WinExe</OutputType>
   <TargetFramework>netcoreapp3.1</TargetFramework>
</PropertyGroup>
```

**Comment by zaafar** [comment]
make sense, will test it out locally and then will update the code.

**Comment by zaafar** [comment]
https://github.com/zaafar/ClickableTransparentOverlay/commit/6780839c270422245a996829b5763d86d4e6aee3
Done.
