### ISSUE TITLE
overlay background is white and not transparent after updating 

### ISSUE THREAD

**Issue by fernandodx1000** [zaafar/ClickableTransparentOverlay#27]
![Screenshot_1](https://user-images.githubusercontent.com/5472587/139591564-9bd4af84-8d5d-49e4-a718-838ea4e76e66.png)

OS: windows 10 pro 19043.1288
nvidia drivers :  v496.49

**Comment by zaafar** [comment]
Nvidia Drivers: v496.49
OS: windows 10 Education (ver: 19043.1288)

Working fine over here. Maybe check your Nvidia settings...
