### ISSUE TITLE
Application focus changes when clicking on a form

### ISSUE THREAD

**Issue by Yarik124421** [zaafar/ClickableTransparentOverlay#29]
Hi, there is such a problem that when you click on the imgui menu, the application behind it loses focus. That is, the click does not reach it. In my case, the application pauses after clicking on imgui, any ideas how to fix this? I also wanted to say thank you for this package, this is a very convenient solution. It would be convenient if you would like to leave any wallet for voluntary donations.

**Comment by zaafar** [comment]
> there is such a problem that when you click on the imgui menu, the application behind it loses focus. That is, the click does not reach it.

ofcourse, that’s the intended behaviour, when user wants to click the ImGui, the OS seamlessly focuses on ImGui and blocks any input to the underlying application. Also, once user is done clicking the ImGui, the OS seamlessly gives the focus back to the underlying application.


If you do not want ImGui to capture control of the mouse/keyboard and do not want OS to pass the control to ImGui, you can always ( at runtime ~ from within the Render loop ) set the ‘ImGuiWindowFlags.NoInputs’ ImGui flag to your ImGui window.


This allows you to have more control in the Render loop to do whatever you wish to do.


> In my case, the application pauses after clicking on imgui, any ideas how to fix this?

sounds like a bug in your application. Your application might be doing something resource intensive on window focus change but yeah, no idea how to fix it or where to start. All I can say that I use this library in my personal project where I create an overlay and there are no pauses when moving from ImGui to the application and vice versa.


> It would be convenient if you would like to leave any wallet for voluntary donations.

Great idea! Will push a change to the readme. Thanks!
