### ISSUE TITLE
Nuget dependency issue

### ISSUE THREAD

**Issue by mbwilding** [zaafar/ClickableTransparentOverlay#35]
Unable to find package Veldrid.StartupUtilities with version (>= 4.9.0-beta1-g416d633c88)
Unable to find package Veldrid.Sdl2 with version (>= 4.9.0-beta1-g416d633c88)
Unable to find package Veldrid.ImageSharp with version (>= 4.9.0-beta1-g416d633c88)
Unable to find package Veldrid with version (>= 4.9.0-beta1-g416d633c88)

Nearest version: 4.9.0-beta1

Is this able to be rectified by uploading a new NuGet/NuSpec with these dependency versions updated?

**Comment by mbwilding** [comment]
Updating the NuSpec file fixed it locally.

[clickabletransparentoverlay.zip](https://github.com/zaafar/ClickableTransparentOverlay/files/8884018/clickabletransparentoverlay.zip)

**Comment by zaafar** [comment]
Did you read https://github.com/zaafar/ClickableTransparentOverlay/issues/19?

**Comment by mbwilding** [comment]
> 

Thanks, applied the change to my repo.
