### ISSUE TITLE
AccessViolationException when create texture when height and width is not same size

### ISSUE THREAD

**Issue by rafadsm** [zaafar/ClickableTransparentOverlay#38]
When i load image `512x512` `128x128`, ... or some size when width and height is same size, it works nice, but if i load image with width and height different, i get the error, a exmple: `512x128`
The error is in `ClickableTransparentOverlay.ImGuiRenderer.CreateImageTexture` when the method calls the `device.CreateTexture2D(...)`
The error message is `System.AccessViolationException: 'Attempted to read or write protected memory. This is often an indication that other memory is corrupt.'`

The problem is in https://github.com/zaafar/ClickableTransparentOverlay/blob/49a3011d7f2ff514489fadf559741ae5355a7d71/ClickableTransparentOverlay/ImGuiRenderer.cs#L213

Looking to the `Texture2DDescription`, the parameters is `format`, `width`, `height`, `.....`, in the current code, using `image.Width` in `height` param

**Comment by zaafar** [comment]
working fine on my side ([code](https://github.com/zaafar/ClickableTransparentOverlay/blob/master/Examples/MultiThreadedOverlay/SampleOverlay.cs#L193)). Can you please send me some sample code to reproduce the issue?


![image](https://user-images.githubusercontent.com/5079646/187103150-ad9fa4a6-ed47-4e91-8576-483e01f21377.png)
