### ISSUE TITLE
Is support for .Net Framework 4.8 and under possible?

### ISSUE THREAD

**Issue by ImmuneLion318** [zaafar/ClickableTransparentOverlay#41]
Yes this question sounds dumb like who would be using .Net Framework still but I have reasons and I could really use if this supported that. Thanks

**Comment by zaafar** [comment]
Yeah this is dumb. However, I will give it a try to see if I can.

**Comment by ImmuneLion318** [comment]
sounds great keep me notified, but yea I accept how dumb this is.

**Comment by zaafar** [comment]
> under possible

how much under you wanna go? or .Net Framework 4.8 is enough?

**Comment by ImmuneLion318** [comment]
> > under possible
> 
> 
> 
> how much under you wanna go? or .Net Framework 4.8 is enough?

4.8 is enough anymore is just complementary for anyone else lol but yea 4.8 is good

**Comment by ImmuneLion318** [comment]
Any luck or just gave up by this point lol

**Comment by zaafar** [comment]
I have some good news and some bad news.

good news is that [net48](https://github.com/zaafar/ClickableTransparentOverlay/tree/f/net48) branch of this repo works with .net framework 4.8.

The bad news is that this branch is made from old code base (i.e. CTO 3.5.0) rather than the latest code (i.e. CTO 6.2.1). This is because latest code have some code that is only available in latest .net c# languages as shown in screenshot below.


![language_8_0_features](https://user-images.githubusercontent.com/5079646/219907853-b7f5c7c4-014d-4efd-8f8a-c8d7fc43d1d8.png)

**Comment by ImmuneLion318** [comment]
Ah my immediate solution would be set the Lang version in the csproj <LangVersion>11.0</LangVersion> but this is amazing already so thanks

**Comment by ImmuneLion318** [comment]
Is it available through nuget in a .Net framework 4.8 project

**Comment by zaafar** [comment]
that's a good idea, here's another branch, see if it works for you.
it support net48 and net7 with lang version 11.0.

https://github.com/zaafar/ClickableTransparentOverlay/tree/f/net7

**Comment by ImmuneLion318** [comment]
Give me a bit my pc is unfortunately pretty bad so if it isn't getting via nuget and I have to build my vs has a stroke and just takes 10 years to do it lol

**Comment by zaafar** [comment]
I haven't released it on nuget yet. Let me do that now.

**Comment by ImmuneLion318** [comment]
i'd appreciate that it would make doing this a whole lot easier on my crappy pc lol

**Comment by ImmuneLion318** [comment]
just let me know when you push the nuget so i can download it to my project

**Comment by zaafar** [comment]
done. give 7.0.0 a try.

**Comment by zaafar** [comment]
hmm, looks like the deps i rely on aren't gonna work on .net 4.8.

![image](https://user-images.githubusercontent.com/5079646/219972748-20a1bcbf-4ab8-483f-a18e-ade315b87868.png)

**Comment by zaafar** [comment]
okay, it works with following .net framework
![image](https://user-images.githubusercontent.com/5079646/219972792-6100b216-8c4c-41cd-ae4e-da333e637457.png)

**Comment by zaafar** [comment]
so this is the only branch that works & it contain old code.
https://github.com/zaafar/ClickableTransparentOverlay/tree/f/net48

**Comment by ImmuneLion318** [comment]
Ok i'll give it a try now i'm on 4.8 i can go to 4.8.1 just fine

**Comment by ImmuneLion318** [comment]
unfortunately i forgot to install net framework 4.8.1 so let me grab it real fast

**Comment by ImmuneLion318** [comment]
I should have red about your deps i just tried via nuget and forgot lol and realized yea the constraints in deps

**Comment by ImmuneLion318** [comment]
Well i got it to start but it appears an exception is thrown

**Comment by ImmuneLion318** [comment]
![image](https://user-images.githubusercontent.com/54381449/219977401-7930a265-ef33-4f52-acb8-50d7ed0bc57b.png)

**Comment by zaafar** [comment]
which branch are you using?

**Comment by ImmuneLion318** [comment]
The latest that builds on 4.8

**Comment by ImmuneLion318** [comment]
![image](https://user-images.githubusercontent.com/54381449/219978132-986e1744-1524-4786-80a1-83890bb1f924.png)
It appears create context is not doing so well at that lol

**Comment by ImmuneLion318** [comment]
I hate that this is causing you so much trouble if you wish to stop and just cease working on below .Net into framework then i'd understand it was just for a side project i had in framework.

**Comment by zaafar** [comment]
not a problem, let me make a nuget release from tag 3.5.0, that should fix your issue.

**Comment by zaafar** [comment]
i have just released version 3.5.1 on nuget. that should fix your issue.

**Comment by zaafar** [comment]
if that doesn't work, then i am out. not sure what else to do. maybe try to move to .net 6 or .net 7.

**Comment by ImmuneLion318** [comment]
I will look into when i'm home from class thanks again I usually use .Net 6/7 but this projects came with the need to use framework unfortunately

**Comment by ImmuneLion318** [comment]
![image](https://user-images.githubusercontent.com/54381449/220198894-bf9f0c0e-a59f-4185-b3d1-ce1f25efc34b.png)
in the 3.5.1 nuget release for me i'm lost rn lol, but it's fine you did work so it's my respect you've earned entirely
