### ISSUE TITLE
Does this ImGui library support the use of glyphs (icons)?

### ISSUE THREAD

**Issue by survivalq** [zaafar/ClickableTransparentOverlay#44]
I came across a code snippet on the internet that loads custom glyphs using ImGui.NET but I'm having trouble getting them to display properly. Even though the glyphs are loaded, they still appear as question marks when I try to use them with Push/Pop font. Do you have any suggestions for how I can troubleshoot this issue and get the glyphs to display correctly?

```cs
        static unsafe ImFontPtr LoadIconFont(string name, int size, (ushort, ushort) range)
        {
            ImFontConfigPtr configuration = ImGuiNative.ImFontConfig_ImFontConfig();

            configuration.MergeMode  = true;
            configuration.PixelSnapH = true;

            // string path = Path.Combine(".", "Resources", "Fonts", name + ".ttf");
            string path = MaterialDesign.FontIconFileNameMD;

            GCHandle rangeHandle = GCHandle.Alloc(new ushort[]
            {
                range.Item1,
                range.Item2,
                0
            }, GCHandleType.Pinned);

            try
            {
                return ImGui.GetIO().Fonts.AddFontFromFileTTF(path, size, configuration, rangeHandle.AddrOfPinnedObject());
            }
            finally
            {
                configuration.Destroy();

                if (rangeHandle.IsAllocated)
                {
                    rangeHandle.Free();
                }
            }
        }
```

**Comment by survivalq** [comment]
I've used the ReplaceFont to get a custom font, but I think it would be beneficial if you could also add an AddGlyphs method.

**Comment by zaafar** [comment]
It’s already supported, I am going to update Example project code to show you how to do it.


Can you share with me the:

1: input file
2: size
3: ranges


Thank you

**Comment by zaafar** [comment]
> it would be beneficial if you could also add an AddGlyphs method.

what’s the purpose of addGlyph method? Do you have such method header/documentation in imgui.net or imgui

**Comment by survivalq** [comment]
> It’s already supported, I am going to update Example project code to show you how to do it.
> 
> Can you share with me the:
> 
> 1: input file 2: size 3: ranges
> 
> Thank you

I used this resource: https://github.com/juliettef/IconFontCppHeaders/blob/main/IconsFontAwesome5.cs to get my icons, hence they already have the .ttf file & ranges

**Comment by zaafar** [comment]
okay now i understand what you want. you want ability to append new (icon) font texture to the existing font texture. Currently CTO only support replacing fonts.

![image](https://github.com/zaafar/ClickableTransparentOverlay/assets/5079646/153daeb1-c6af-49f1-a5b6-0d07071313a7)

**Comment by survivalq** [comment]
> I have the same issue using: [https://github.com/juliettef/IconFontCppHeaders/blob/main/IconsFontAwesome6.cs](url)
> 
> ```
>                 string solidFont = Path.Combine(BepInEx.Paths.PluginPath + "fa-solid-900.ttf");
>                 ImGui.PushFont(faSolid);
>                 ushort[] glyphRange = new ushort[FontAwesome6.IconMax - FontAwesome6.IconMin + 1];
>                 for (int i = 0; i < glyphRange.Length; i++)
>                 {
>                     glyphRange[i] = (ushort)(FontAwesome6.IconMin + i);
>                 }
>                 ImGui.Begin("Sample Overlay", ref OverlayState.ShowOverlay, ImGuiWindowFlags.AlwaysAutoResize);
>                 ReplaceFont(solidFont, 16, glyphRange);
>                 ImGui.Text(FontAwesome6.PowerOff);
>                 ImGui.End();
> ```
> 
> The result show up as "?" ![image](https://user-images.githubusercontent.com/52474054/241759326-08d473c8-519f-45a8-81aa-9f84414b87d8.png)

Yep, I think he is already working on the solution for that.

**Comment by krulci** [comment]
> > I have the same issue using: [https://github.com/juliettef/IconFontCppHeaders/blob/main/IconsFontAwesome6.cs](url)
> > ```
> >                 string solidFont = Path.Combine(BepInEx.Paths.PluginPath + "fa-solid-900.ttf");
> >                 ImGui.PushFont(faSolid);
> >                 ushort[] glyphRange = new ushort[FontAwesome6.IconMax - FontAwesome6.IconMin + 1];
> >                 for (int i = 0; i < glyphRange.Length; i++)
> >                 {
> >                     glyphRange[i] = (ushort)(FontAwesome6.IconMin + i);
> >                 }
> >                 ImGui.Begin("Sample Overlay", ref OverlayState.ShowOverlay, ImGuiWindowFlags.AlwaysAutoResize);
> >                 ReplaceFont(solidFont, 16, glyphRange);
> >                 ImGui.Text(FontAwesome6.PowerOff);
> >                 ImGui.End();
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The result show up as "?" ![image](https://user-images.githubusercontent.com/52474054/241759326-08d473c8-519f-45a8-81aa-9f84414b87d8.png)
> 
> Yep, I think he is already working on the solution for that.

You mentioned using ReplaceFont. Does the api work to load gliphy? Just wondering if I am using it wrong.

**Comment by krulci** [comment]
> 

You mean like just regular text, but not gliph?

**Comment by survivalq** [comment]
> > 
> 
> You mean like just regular text, but not gliph?

Yes

**Comment by zaafar** [comment]
With existing replace font  you can load any font, but the limitation is that, you can load just 1 font at any given point in time. What this issue is asking for is to load multiple fonts and merge them together.

**Comment by krulci** [comment]
> With existing replace font you can load any font, but the limitation is that, you can load just 1 font at any given point in time. What this issue is asking for is to load multiple fonts and merge them together.

How would you setup as to just load one font and show the glyph?

**Comment by krulci** [comment]
> With existing replace font you can load any font, but the limitation is that, you can load just 1 font at any given point in time. What this issue is asking for is to load multiple fonts and merge them together.

I was able to use ReplaceFont now.
And, I understand this issue now.
ReplacceFont seems to only replace the entire font instead of appending/merging them.
I tried the following:
```cs
public void UpdateFontTexture(string fontPathName, float fontSize, ushort[]? fontCustomGlyphRange, FontGlyphRangeType fontLanguage)
        {
            var io = ImGui.GetIO();
            this.DeRegisterTexture(io.Fonts.TexID)?.Dispose();
            io.Fonts.Clear();
            var config = ImGuiNative.ImFontConfig_ImFontConfig();
            config->MergeMode = 1; // Set MergeMode to True
```
The Process will just crash.

**Comment by krulci** [comment]
So after font is loaded and if I do something like this:
```cs
ImGui.SameLine();
ToggleButton(FontAwesome6.Gear + " Options", ref m_showOptions);
```
The result will be:
![image](https://github.com/zaafar/ClickableTransparentOverlay/assets/52474054/278e566a-0ccc-408b-b593-892d1ffc9956)

**Comment by krulci** [comment]
I think I figure how to get merging work
So basically, the first font loaded you **Do Not** set the `MergeMode` on
After the first `AddFontFromFileTTF` is called you set the `MergeMode` on
```cs
public void UpdateFontTexture(string fontPathName, float fontSize, ushort[]? fontCustomGlyphRange, FontGlyphRangeType fontLanguage)
        {
            var io = ImGui.GetIO();
            this.DeRegisterTexture(io.Fonts.TexID)?.Dispose();
            io.Fonts.Clear();
            var config = ImGuiNative.ImFontConfig_ImFontConfig();
            if (fontCustomGlyphRange == null)
            {
                /// ...
            }
            else
            {
                ushort[] rangesBasic =
                {
                    0x0020, 0x00FF, // Basic Latin + Latin Supplement
                    0x03BC, 0x03BC, // micro
                    0x03C3, 0x03C3, // small sigma
                    0x2013, 0x2013, // en dash
                    0x2264, 0x2264, // less-than or equal to
                    0
                };
                fixed (ushort* q = &rangesBasic[0])
                {
                    string droidSans = "C:\\path\\DroidSans.ttf";
                    io.Fonts.AddFontFromFileTTF(droidSans, fontSize, config, new IntPtr(q));
                }
                fixed (ushort* p = &fontCustomGlyphRange[0])
                {
                    config->MergeMode = 1;
                    io.Fonts.AddFontFromFileTTF(fontPathName, fontSize, config, new IntPtr(p));
                }
            }

            this.CreateFontsTexture();
            ImGuiNative.ImFontConfig_destroy(config);
        }
```

**Comment by krulci** [comment]
I am targeted my fork to Net 6.0 so probably won't be able to submit a pull request.
But, I implemented `ReplaceFontMultiples`
https://github.com/krulci/ClickableTransparentOverlay/commit/93a75abdd2042c0bbe5da3575fdb347abe19de3a

**Comment by survivalq** [comment]
> I targeted my fork to Net 6.0 so probably won't be able to submit a pull request. But, I implemented `ReplaceFontMultiples`, `UpdateFontTextures`, `ReplaceFontMultipleIfRequired` [krulci@93a75ab](https://github.com/krulci/ClickableTransparentOverlay/commit/93a75abdd2042c0bbe5da3575fdb347abe19de3a)

Could you also update that fork's example(s) on how to use the methods you've added? And I think the .net 6 fork works well on .net 7 as of my testing

**Comment by krulci** [comment]
> > I targeted my fork to Net 6.0 so probably won't be able to submit a pull request. But, I implemented `ReplaceFontMultiples`, `UpdateFontTextures`, `ReplaceFontMultipleIfRequired` [krulci@93a75ab](https://github.com/krulci/ClickableTransparentOverlay/commit/93a75abdd2042c0bbe5da3575fdb347abe19de3a)
> 
> Could you also update that fork's example(s) on how to use the methods you've added? And I think the .net 6 fork works well on .net 7 as of my testing

I am currently on a business trip; will provide an example after then. However, if you just want to know how to use it, is pretty much the same as the original method. You are just passing in an array of fonts you want to merge and override as the default font. So for example, the original method is taking single object for each parameters. The merge method is just taking an array of objects for each parameters. So if you have 3 fonts to merge, you just create an array or the parameter types and add the object in sequence. The nth object in the array of a parameter has to match the nth object in the array of another parameters.

**Comment by NustyFrozen** [comment]
A fix: [https://github.com/zaafar/ClickableTransparentOverlay/discussions/49](url)

```
var dictionary = new Dictionary<string, Tuple<string, float, FontGlyphRangeType, ushort[]>>();
            dictionary.Add("MyFirstFont", new Tuple<string, float, FontGlyphRangeType, ushort[]>(@"Segoe.ttf", 24, FontGlyphRangeType.English, null));
            dictionary.Add("MySecondFont", new Tuple<string, float, FontGlyphRangeType, ushort[]>(@"Poppins.ttf", 18, FontGlyphRangeType.English, null));
            dictionary.Add("IconFont", new Tuple<string, float, FontGlyphRangeType, ushort[]>(@"fa-regular-400.ttf", 18, FontGlyphRangeType.English, new ushort[] { 0xe005,
            0xf8ff,0}));
            this.InitializeFonts(dictionary);
            ImFontPtr myFont = this.getFontByLabel("MyFirstFont");
            ImFontPtr secondFont = this.getFontByLabel("MySecondFont");
            ImFontPtr iconfont = this.getFontByLabel("IconFont");
            ImGui.PushFont(myFont);
            ImGui.Text("I am using my first font");
            ImGui.PopFont();
            ImGui.PushFont(secondFont);
            ImGui.Text("I am using my second font");
            ImGui.PopFont();
            ImGui.PushFont(iconfont);
            ImGui.Text("Book:" + "\uf2b9");
            ImGui.PopFont();
```
![image](https://github.com/zaafar/ClickableTransparentOverlay/assets/43705995/df3a1dbc-7ef7-4031-9ed2-8b7e34600dd9)

**Comment by zaafar** [comment]
example code https://github.com/zaafar/ClickableTransparentOverlay/blob/master/Examples/SingleThreadedOverlayWithCoroutines/SampleOverlay.cs#L165
