### ISSUE TITLE
Does this IMGUI library support the use of DockNode?

### ISSUE THREAD

**Issue by krulci** [zaafar/ClickableTransparentOverlay#46]
Not sure if I am not using it correctly, but I can't seem to find 

ImGui::DockBuilderSplitNode

ImGui::DockBuilderGetNode

ImGui::DockBuilderDockWindow

And related APIs

**Comment by krulci** [comment]
Did some research.
Seems like I need to change ImGui using this branch:
[https://github.com/ImGuiNET/ImGui.NET/pull/273](url)

**Comment by zaafar** [comment]
ImGui internal APIs are part of imgui.net lib.

**Comment by krulci** [comment]
> ImGui internal APIs are part of imgui.net lib.

Sorry, just started to get back to my project.
How do you use them if you said there are in IMGUI.NET?

**Comment by zaafar** [comment]
Sorry, that was a typo.

I mean, imgui internal API are not part of imgui.net lib. So I can't provide them in this library.
