### ISSUE TITLE
Add color picker i first windows

### ISSUE THREAD

**Issue by Cesar1986BR** [zaafar/ClickableTransparentOverlay#5]
Hi im little bit confuse, how i can add a color picker in first windows menu imgui?

**Comment by zaafar** [comment]
I normally look at the [ImGui Demo Window](https://github.com/ocornut/imgui/blob/7c51cba74f4a871c502cf291bc0d134cf41e3bd4/imgui_demo.cpp) code for all the references. It's c++ code but very similar to ImGui C# API.

To answer your question here's what you can use.
`
private static Vector4 foo = Vector4.Zero;
ImGui.ColorPicker4("testing", ref foo);
`

NOTE: For Vector4 struct you need to install System.Numerics.Vectors from NuGet

**Comment by Cesar1986BR** [comment]
yeah thx, i already get, but i dont understand somethings, for example how to do for  menu  use a windows already open, i have Battlefield V game windows open and i want o menu open using this windows, not overlay

**Comment by zaafar** [comment]
Correct me if I am wrong, you want to draw on the menu inside the Battlefield V game?
If that's the case then this library wouldn't help you achieve that. This library is all about drawing stuff on the overlay so you don't have to inject data/dll/stuff into the game.
