### ISSUE TITLE
Screen Position Error on the latest version

### ISSUE THREAD

**Issue by MetalDeveloper** [zaafar/ClickableTransparentOverlay#61]
on the latest version of CTO it messes up the screen size. I fixed it by downgrading the version.

**Comment by zaafar** [comment]
You can always change the size with help of the Size api ( https://github.com/zaafar/ClickableTransparentOverlay/blob/master/ClickableTransparentOverlay/Overlay.cs#L280 ). In the old version of the lib, the default size was the screen size. In the new version of the lib, default size is 800x600 and it’s expected the user of the library to set the size to whatever they want.
