### ISSUE TITLE
Scaling issues in version >= 9.2.0

### ISSUE THREAD

**Issue by TwoTenPvP** [zaafar/ClickableTransparentOverlay#67]
In version 9.2.0 and above, menus cannot be dragged or used across the whole window size.
Works properly in 9.1

**Comment by zaafar** [comment]
Users of this lib are allowed to modify window size as well as make it full screen. Doing so will allow you to re-produce the 9.1 behaviour. Let me know if you need anything else.

**Comment by ErickCHIN000** [comment]
> Users of this lib are allowed to modify window size as well as make it full screen. Doing so will allow you to re-produce the 9.1 behaviour. Let me know if you need anything else.

i have no idea how to go about doing that, could you share an example or point me to one?

**Comment by zaafar** [comment]
> > Users of this lib are allowed to modify window size as well as make it full screen. Doing so will allow you to re-produce the 9.1 behaviour. Let me know if you need anything else.
> 
> i have no idea how to go about doing that, could you share an example or point me to one?

https://github.com/zaafar/ClickableTransparentOverlay/blob/master/Examples/MultiThreadedOverlay/SampleOverlay.cs#L139

**Comment by zaafar** [comment]
now you can do it in class constructor as well as shown below.
https://github.com/zaafar/ClickableTransparentOverlay/blob/master/Examples/SimpleExample/SampleOverlay.cs#L11
