### ISSUE TITLE
Set Overlay window to Fullscreen

### ISSUE THREAD

**Issue by PhilCode-creator** [zaafar/ClickableTransparentOverlay#70]
Hello I am trying to have the overlay cover my entierty of my screen not just a small area I tried doing ImGui#SetNextWindowSize but that only resized the ImGui window not the actual overlay 
please let me know how to fix that thanks,

**Comment by zaafar** [comment]
did you try changing overlay class `Size` property?

**Comment by PhilCode-creator** [comment]
I was on the wrong version mb
