### ISSUE TITLE
White Screen and Scaling Glitch

### ISSUE THREAD

**Issue by Snawalt** [zaafar/ClickableTransparentOverlay#72]
In version 9.1, the ui sometimes turns white randomly before returning to normal. However, when using version 9.2 or later, the white screen issue is resolved, but there's a new problem: the ui cannot be fully displayed in fullscreen mode. Part of the screen seems to disappear, indicating a possible screen scaling issue, any idea to fix this?

![Untitled](https://github.com/zaafar/ClickableTransparentOverlay/assets/69634294/b21255a7-77ed-459d-9ed0-9349c7276d62)

**Comment by zaafar** [comment]
In 9.2 or later you have to use the Overlay `Size` property to set the overlay to your fullscreen size.
You can do this during start up (constructor) or in the render function.
