### ISSUE TITLE
Latest update

### ISSUE THREAD

**Issue by TheSadCollector** [zaafar/ClickableTransparentOverlay#73]
Seems like the last few updates has broken the resolution and only does about half the screen. Also I wanted to ask if there an option to disable the transparent background on the imgui menus? Changing the alpha seems to do nothing but I just want it a solid colour.

**Comment by zaafar** [comment]
try doing something like this and see if it fixes the issue.
https://github.com/zaafar/ClickableTransparentOverlay/blob/master/Examples/SimpleExample/SampleOverlay.cs#L11

> Also I wanted to ask if there an option to disable the transparent background on the imgui menus? Changing the alpha seems to do nothing but I just want it a solid colour.

do u have an example screenshot of what you want vs what you are getting.

**Comment by TheSadCollector** [comment]
> try doing something like this and see if it fixes the issue. https://github.com/zaafar/ClickableTransparentOverlay/blob/master/Examples/SimpleExample/SampleOverlay.cs#L11
> 
> > Also I wanted to ask if there an option to disable the transparent background on the imgui menus? Changing the alpha seems to do nothing but I just want it a solid colour.
> 
> do u have an example screenshot of what you want vs what you are getting.

Ah, that example worked great! Thank you. Only issue so far is when I change the alpha in ShowStyleEditor for any colour it seems to cause a crash with the error "Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt."

**Comment by zaafar** [comment]
if you can reproduce this issue in any one of the example projects (i.e. https://github.com/zaafar/ClickableTransparentOverlay/tree/master/Examples) i will take a look at it.
