### ISSUE TITLE
Could not install package

### ISSUE THREAD

**Issue by anastasiosskg** [zaafar/ClickableTransparentOverlay#74]
I get this error message when i click on install button :

Severity	Code	Description	Project	File	Line	Suppression State	Details
Error		Could not install package 'ClickableTransparentOverlay 10.1.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.7.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by zaafar** [comment]
You need to move your project to .net 7.

.net framework is old technology and isn’t supported anymore.
